table proBed
"BED12+13 PSI proBed 1.0.0"
(
string  chrom;  "Reference sequence chromosome"
uint  chromStart;  "Start position of the first DNA base"
uint  chromEnd;  "End position of the last DNA base"
string  name;  "Unique name"
uint  score;  "Score"
char[1]  strand;  "+ or - for strand"
uint  thickStart;  "Coding region start"
uint  thickEnd;  "Coding region end"
uint  reserved;  "Always 0"
int  blockCount;  "Number of blocks"
int[blockCount]  blockSizes;  "Block sizes"
int[blockCount]  chromStarts;  "Block starts"
string  proteinAccession;  "Protein accession number"
string  peptideSequence;  "Peptide sequence"
string  uniqueness;  "Peptide uniqueness"
string  genomeReferenceVersion;  "Genome reference version number"
double  psmScore;  "PSM score"
double  fdr;  "False-discovery rate"
string  modifications;  "Post-translational modifications"
int  charge;  "Charge value"
double  exp_mass_to_charge;  "Experimental mass to charge value"
double  calcMassToCharge;  "Calculated mass to charge value"
int  psmRank;  "Peptide-Spectrum Match rank."
string  datasetID;  "Dataset Identifier"
string  uri;  "Uniform Resource Identifier"
)